version: '3'

services:

  controller:
    build: ./fenswood_drone_controller
    command: ros2 launch fenswood_drone_controller controller_finite_state.launch.xml

  simhost:
    image: uobflightlabstarling/starling-sim-iris-ap-fenswood:latest
    environment:
      - AP_SITL_HOST=sitl
    ports:
      - "8080:8080"

  sitl:
    image: uobflightlabstarling/starling-sim-ardupilot-copter:v0.0.8
    environment:
      - AP_USE_GAZEBO=true
      - AP_HOME=51.4233628,-2.671671,100.0,0
      - AP_SIM_HOST=simhost
  
  mavros:
    image: uobflightlabstarling/starling-mavros:v0.1.0
    command: ros2 launch launch/mavros_bridge.launch.xml
    environment:
      - "MAVROS_TGT_FIRMWARE=apm"
      - "MAVROS_TGT_SYSTEM=1"
      - "MAVROS_FCU_URL=tcp://sitl:5760"
      - "MAVROS_GCS_URL=tcp-l://:5761"
      - "MAVROS_CONFIG_PATH=/mavros_config_ap.yaml"
      - "MAVROS_PLUGINLISTS_PATH=/mavros_pluginlists_ap.yaml"
    ports:
      - "5761:5761"

  rosbridge-suite:
    image: uobflightlabstarling/rosbridge-suite:v0.1.0
    ports:
      - "9090:9090"